using DepotFlow.Domain.Billing;

namespace DepotFlow.Domain.Entities;

public class Invoice
{
    private Invoice() { }   // for EF Core

    /// <summary>
    /// Issues the invoice for a visit that is leaving. Free days, strategy, currency and the rates are copied
    /// onto the invoice, so editing or deactivating the tariff later cannot change it. A zero total is born Paid.
    /// </summary>
    public static Invoice Issue(Visit visit, TariffSnapshot tariff, int dwellDays, ChargeResult charge, DateTime issuedAtUtc)
    {
        var invoice = new Invoice
        {
            Visit = visit,
            VisitId = visit.Id,
            ShippingLineId = visit.ShippingLineId,
            IssuedAtUtc = issuedAtUtc,
            DwellDays = dwellDays,
            FreeDays = tariff.FreeDays,
            StrategyKey = tariff.StrategyKey,
            Currency = tariff.Currency,
            Total = charge.Total,
            Status = InvoiceStatus.Issued,
            Lines = charge.Lines.Select(l => new InvoiceLine(l)).ToList()
        };

        if (charge.Total == 0)
        {
            invoice.Status = InvoiceStatus.Paid;
            invoice.PaidAtUtc = issuedAtUtc;
        }

        return invoice;
    }

    public long Id { get; private set; }

    /// <summary>Generated by the database from a sequence, for example INV-2026-0000123.</summary>
    public string InvoiceNumber { get; private set; } = null!;

    public long VisitId { get; private set; }
    public Visit Visit { get; private set; } = null!;
    public int ShippingLineId { get; private set; }
    public DateTime IssuedAtUtc { get; private set; }
    public int DwellDays { get; private set; }
    public int FreeDays { get; private set; }
    public string StrategyKey { get; private set; } = null!;
    public string Currency { get; private set; } = null!;
    public decimal Total { get; private set; }
    public InvoiceStatus Status { get; private set; }
    public DateTime? PaidAtUtc { get; private set; }
    public string? PaidByUserId { get; private set; }

    public List<InvoiceLine> Lines { get; private set; } = [];

    public void Pay(DateTime paidAtUtc, string paidByUserId)
    {
        if (Status == InvoiceStatus.Paid)
        {
            throw new DomainException("Invoice has already been paid.");
        }

        Status = InvoiceStatus.Paid;
        PaidAtUtc = paidAtUtc;
        PaidByUserId = paidByUserId;
    }
}
